// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBopqYJ8ZHBEMORqzkBpRWVUgfPNqEtY80',
    appId: '1:586406917964:web:793bee83984da0f8d381e9',
    messagingSenderId: '586406917964',
    projectId: 'just-tickets-4d084',
    authDomain: 'just-tickets-4d084.firebaseapp.com',
    storageBucket: 'just-tickets-4d084.appspot.com',
    measurementId: 'G-7CWD0H9B8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHz2nVoct-Q3egs7yi-KtB90vtMIvcOGE',
    appId: '1:586406917964:android:5b3d1ca33166cf55d381e9',
    messagingSenderId: '586406917964',
    projectId: 'just-tickets-4d084',
    storageBucket: 'just-tickets-4d084.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlDr9iDfLnmEMraCAmJT1e3xhjyKZemCI',
    appId: '1:586406917964:ios:c2fec568d22de36bd381e9',
    messagingSenderId: '586406917964',
    projectId: 'just-tickets-4d084',
    storageBucket: 'just-tickets-4d084.appspot.com',
    iosBundleId: 'com.example.justTickets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlDr9iDfLnmEMraCAmJT1e3xhjyKZemCI',
    appId: '1:586406917964:ios:c2fec568d22de36bd381e9',
    messagingSenderId: '586406917964',
    projectId: 'just-tickets-4d084',
    storageBucket: 'just-tickets-4d084.appspot.com',
    iosBundleId: 'com.example.justTickets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBopqYJ8ZHBEMORqzkBpRWVUgfPNqEtY80',
    appId: '1:586406917964:web:ce25a7b18545732ed381e9',
    messagingSenderId: '586406917964',
    projectId: 'just-tickets-4d084',
    authDomain: 'just-tickets-4d084.firebaseapp.com',
    storageBucket: 'just-tickets-4d084.appspot.com',
    measurementId: 'G-DQ2YCJ108S',
  );
}
